spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bookmanger?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#mybatis.config-location=classpath:mapper/config/SqlMapConfig.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

